### ISSUE TITLE
Perception?

### ISSUE THREAD

**Issue by IronWarjack** [EthanJWright/foundryvtt-importer#43] opened 2022-05-02 13:19 UTC
I assuming this is a feature req and that the code does not do this currently, but it appears passive Perception x is not begin added to the actor.

Senses passive Perception 10
https://i.imgur.com/KGg1OJb.png

**Comment by EthanJWright** [comment] 2022-05-04 02:13
Passive perception actually should be added I believe, would you mind sharing the text block of the monster you're importing and I can add a test for it/see why it isn't being added?

**Comment by grungyape** [comment] 2022-05-04 12:25
Ethan,

Happy to, I am importing from Privateer Press new 5e Iron Kingdoms books.

I am including two examples.

Example 1:

How it looks in the book:  https://i.imgur.com/ohXYggq.png
Here is the "copy/paste" text:

===========================================
Bloodstone Bison
Large beast, unaligned
Armor Class 10
Hit Points 28 (3d10 + 12)
Speed 40 ft.
STR DEX CON INT WIS CHA
17 (+3) 10 (+0) 19 (+4) 18 (+4) 16 (+3) 3 (−4)
Senses passive Perception 10
Languages —
Challenge 1/2 (100 XP)
Hardy. The bison has advantage on saving throws against effects
that cause exhaustion.
Charge. If the bison moves at least 20 feet straight toward a
target and then hits it with a gore attack on the same turn, the
target takes an extra 5 (2d4) piercing damage. If the target is a
creature, it must succeed on a DC 13 Strength saving throw or be
knocked prone.
Actions
Gore. Melee Weapon Attack: +5 to hit, reach 5 ft., one
target. Hit: 10 (2d6 + 3) piercing damage.
Hooves. Melee Weapon Attack: +5 to hit, reach 5 ft., one prone
creature. Hit: 13 (4d4 + 3) bludgeoning damage.
===========================================

Example 2:

How it looks in the book:   https://i.imgur.com/xjdmk2J.png
Here is the "copy/paste" text:

===========================================
Archidon
Large monstrosity, neutral evil
Armor Class 14 (natural armor)
Hit Points 75 (10d10 + 20)
Speed 20 ft., fly 60 ft.
STR DEX CON INT WIS CHA
20 (+5) 16 (+3) 14 (+2) 4 (–3) 10 (+0) 10 (+0)
Damage Immunities lightning
Condition Immunities frightened
Senses passive Perception 10
Languages —
Challenge 4 (1,100 XP)
Wind Rider. An archidon’s movement speed while flying is not
affected by strong winds.
Actions
Multiattack. The archidon uses Pitch if it has a creature
grappled at the start of its turn. It then makes two bite attacks.
Bite. Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit:
11 (1d12 + 5) piercing damage. If the target is a Medium or smaller
creature, it is grappled (escape DC 15). Until this grapple ends,
the target is restrained, and the archidon can’t use its bite on
another target.
Pitch. If the archidon has a target creature grappled, it can
throw the target 20 feet. The grappled creature must succeed
on a DC 15 Dexterity saving throw or take 7 (2d6) bludgeoning
damage and be knocked prone, in addition to any falling damage
caused by the throw.
===========================================

Side note, not included in my original post, I discovered after, but two
more things.

1. It sets the AC as "flat" even though example 2 says "natural armor"
2. It also leaves the HP calculation blank, instead of setting 10d10+20

Thanks for taking a look!

Thank you,
Frank

About Me: https://grungyape.com
Certified Horsemanship Association Member
Sigma Pi - Gamma '94, Ohio State University
F&AM - Celina Lodge #241, AASR Valley of Dayton
SCA - Frakki dróttinn Pétrsson, 11c Denmark (AKA geitskegg)

*"Quis custodiet ipsos custodes?"*

**Comment by EthanJWright** [comment] 2022-05-04 14:57
Thanks so much for this data! I'll take a look when I get a little bit of time!

**Comment by EthanJWright** [comment] 2022-05-30 20:35
@IronWarjack used your data to make sure the HP formula is getting added when possible, and add some mappings for natural armor.

Upon a second review, I believe 'passive perception' actually doesn't go in senses (seems weird, but you can click the cog next to it to see what the options are) Instead, if you hover over the number in parens () next to perception, you should see that as the passive perception, and it looks like that is getting loaded correctly.

Sorry it took so long for me to look into this, fell down an elden ring hole.

Going to close this and merge the changes, let me know if there are any other issues!

**Closed by EthanJWright** 2022-05-30 20:35 UTC

**Comment by IronWarjack** [comment] 2022-05-31 11:54
Ethan,

Thank you.  I went back and looked at Foundry, I guess I (thought|assumed)
passive Perception went into senses as a free form line item.
However, on your info I went and looked again and apparently I was looking
at someone's custom monster, not an official SRD release.  I'm sorry about
that, but I do appreciate the rest!

Thank you,
Frank (Lars)

About Me: https://grungyape.com
Certified Horsemanship Association Member
Sigma Pi - Gamma '94, Ohio State University
F&AM - Celina Lodge #241, AASR Valley of Dayton
SCA - Frakki dróttinn Pétrsson, 11c Denmark (AKA geitskegg)

*"Quis custodiet ipsos custodes?"*
